# Generated by Django 5.0.2 on 2025-03-19 21:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                ("content", models.TextField(verbose_name="内容")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("notice", "通知"),
                            ("announcement", "公告"),
                            ("warning", "警告"),
                        ],
                        default="notice",
                        max_length=20,
                        verbose_name="公告类型",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否激活")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "系统公告",
                "verbose_name_plural": "系统公告",
                "ordering": ["-created_at"],
            },
        ),
    ]
