# Generated by Django 5.0.2 on 2025-03-19 21:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("announcement", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="announcement",
            name="is_active",
        ),
    ]
