# Generated by Django 5.0.2 on 2025-09-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("announcement", "0002_remove_announcement_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("horizontal", "横向"),
                    ("innovation", "大创"),
                    ("hardware", "硬件小组"),
                    ("assessment", "考核小组"),
                    ("documentation", "材料撰写"),
                    ("assistant", "助教"),
                    ("other", "其他"),
                ],
                help_text="若该公告与某个工作来源相关，请选择",
                max_length=20,
                null=True,
                verbose_name="工作来源",
            ),
        ),
    ]
