# Generated by Django 5.1.6 on 2025-03-13 06:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Workload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="工作量名称")),
                ("content", models.TextField(verbose_name="工作内容")),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("horizontal", "横向"),
                            ("innovation", "大创"),
                            ("hardware", "硬件小组"),
                            ("assessment", "考核小组"),
                        ],
                        max_length=20,
                        verbose_name="工作来源",
                    ),
                ),
                (
                    "work_type",
                    models.CharField(
                        choices=[("remote", "远程"), ("onsite", "实地")],
                        max_length=20,
                        verbose_name="工作类型",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="开始日期")),
                ("end_date", models.DateField(verbose_name="结束日期")),
                (
                    "intensity_type",
                    models.CharField(
                        choices=[("total", "总计"), ("daily", "每天"), ("weekly", "每周")],
                        max_length=20,
                        verbose_name="工作强度类型",
                    ),
                ),
                (
                    "intensity_value",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0.0)],
                        verbose_name="工作强度值",
                    ),
                ),
                (
                    "image_path",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="图片路径"
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="文件路径"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待审核"),
                            ("mentor_approved", "导师已审核"),
                            ("teacher_approved", "教师已审核"),
                            ("mentor_rejected", "导师已驳回"),
                            ("teacher_rejected", "教师已驳回"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="审核状态",
                    ),
                ),
                (
                    "mentor_comment",
                    models.TextField(blank=True, null=True, verbose_name="导师评论"),
                ),
                (
                    "teacher_comment",
                    models.TextField(blank=True, null=True, verbose_name="教师评论"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviewing_workloads",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="审核者",
                    ),
                ),
                (
                    "submitter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submitted_workloads",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="提交者",
                    ),
                ),
            ],
            options={
                "verbose_name": "工作量",
                "verbose_name_plural": "工作量",
                "ordering": ["-created_at"],
            },
        ),
    ]
