# Generated by Django 5.1.6 on 2025-03-15 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workload", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workload",
            name="reviewer",
        ),
        migrations.AddField(
            model_name="workload",
            name="mentor_review_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="导师审核时间"),
        ),
        migrations.AddField(
            model_name="workload",
            name="mentor_reviewer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mentor_reviewing_workloads",
                to=settings.AUTH_USER_MODEL,
                verbose_name="导师审核人",
            ),
        ),
        migrations.AddField(
            model_name="workload",
            name="teacher_review_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="教师审核时间"),
        ),
        migrations.AddField(
            model_name="workload",
            name="teacher_reviewer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="teacher_reviewing_workloads",
                to=settings.AUTH_USER_MODEL,
                verbose_name="教师审核人",
            ),
        ),
        migrations.AlterField(
            model_name="workload",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待审核"),
                    ("mentor_approved", "导师已审核"),
                    ("mentor_rejected", "导师已驳回"),
                    ("teacher_approved", "教师已审核"),
                    ("teacher_rejected", "教师已驳回"),
                ],
                default="pending",
                max_length=20,
                verbose_name="审核状态",
            ),
        ),
    ]
