# Generated by Django 5.0.2 on 2025-03-19 15:35

import workload.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "workload",
            "0002_remove_workload_reviewer_workload_mentor_review_time_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workload",
            name="file_path",
        ),
        migrations.RemoveField(
            model_name="workload",
            name="image_path",
        ),
        migrations.AddField(
            model_name="workload",
            name="attachments",
            field=models.FileField(
                blank=True,
                help_text="支持上传图片、文档等文件",
                max_length=500,
                null=True,
                upload_to=workload.models.workload_file_path,
                verbose_name="附件",
            ),
        ),
    ]
