# Generated by Django 5.0.2 on 2025-08-04 21:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "workload",
            "0003_remove_workload_file_path_remove_workload_image_path_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="workload",
            name="source",
            field=models.CharField(
                choices=[
                    ("horizontal", "横向"),
                    ("innovation", "大创"),
                    ("hardware", "硬件小组"),
                    ("assessment", "考核小组"),
                    ("documentation", "材料撰写"),
                    ("other", "其他"),
                ],
                max_length=20,
                verbose_name="工作来源",
            ),
        ),
    ]
