# Generated by Django 5.0.2 on 2025-09-01 20:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workload", "0004_alter_workload_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workload",
            name="source",
            field=models.CharField(
                choices=[
                    ("horizontal", "横向"),
                    ("innovation", "大创"),
                    ("hardware", "硬件小组"),
                    ("assessment", "考核小组"),
                    ("documentation", "材料撰写"),
                    ("assistant", "助教"),
                    ("other", "其他"),
                ],
                max_length=20,
                verbose_name="工作来源",
            ),
        ),
    ]
