# Generated by Django 5.0.2 on 2025-09-01 20:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workload", "0005_alter_workload_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="workload",
            name="assistant_salary_paid",
            field=models.IntegerField(
                blank=True, help_text="仅当工作来源为助教时需要填写", null=True, verbose_name="已发助教工资"
            ),
        ),
        migrations.AddField(
            model_name="workload",
            name="innovation_stage",
            field=models.CharField(
                blank=True,
                choices=[("before", "立项前"), ("after", "立项后")],
                help_text="仅当工作来源为大创时需要填写",
                max_length=20,
                null=True,
                verbose_name="大创阶段",
            ),
        ),
    ]
