# Generated by Django 5.0.2 on 2025-09-03 12:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workload", "0006_workload_assistant_salary_paid_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkloadShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "percentage",
                    models.FloatField(
                        help_text="当前用户的工作量占比，总和必须为100",
                        validators=[django.core.validators.MinValueValidator(0.0)],
                        verbose_name="占比",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workload_shares",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="参与用户",
                    ),
                ),
                (
                    "workload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="workload.workload",
                        verbose_name="关联工作量",
                    ),
                ),
            ],
            options={
                "verbose_name": "工作量占比",
                "verbose_name_plural": "工作量占比",
                "unique_together": {("workload", "user")},
            },
        ),
    ]
