# Generated by Django 5.0.2 on 2025-09-08 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0001_initial"),
        ("workload", "0007_workloadshare"),
    ]

    operations = [
        migrations.AddField(
            model_name="workload",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="project.project",
                verbose_name="关联项目",
            ),
        ),
    ]
