# Generated by Django 5.0.2 on 2025-09-04 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='项目名称')),
                ('project_status', models.CharField(choices=[('pre_research', '预研'), ('in_research', '在研')], max_length=20, verbose_name='项目状态')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('review_status', models.CharField(choices=[('pending', '待审核'), ('approved', '教师已审核'), ('rejected', '教师已驳回')], default='pending', max_length=20, verbose_name='审核状态')),
                ('teacher_comment', models.TextField(blank=True, null=True, verbose_name='教师评论')),
                ('teacher_review_time', models.DateTimeField(blank=True, null=True, verbose_name='教师审核时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_projects', to=settings.AUTH_USER_MODEL, verbose_name='提交者')),
                ('teacher_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_reviewing_projects', to=settings.AUTH_USER_MODEL, verbose_name='教师审核人')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'ordering': ['-created_at'],
            },
        ),
    ]
