# Generated by Django 5.0.2 on 2025-09-11 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='project.project', verbose_name='项目参与者')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_shares', to=settings.AUTH_USER_MODEL, verbose_name='参与用户')),
            ],
            options={
                'verbose_name': '项目参与情况',
                'verbose_name_plural': '项目参与情况',
                'unique_together': {('project', 'user')},
            },
        ),
    ]
